### ISSUE TITLE
cli 1.7.0 with utf-8 is not work for launchpad shell header

### ISSUE THREAD

**Issue by SupayaT** [SAP/ui5-cli#230] opened 2019-08-19 09:32 UTC
## Expected Behavior
Can display the correct UTF-8 text on launchpad shell header.

## Current Behavior
I use the last published version of cli  (1.7.0 version) to build ui5 application and deploy to the system with web-ide. Then, The launchpad shell header display with ������ So, I see the component-preload file on the i18n_th text is encoded to ascii. Let me know how could I do for this case or maybe add any code in ui5.yaml file?

## Steps to reproduce the issue
1. Create new simple ui5 application and use i18n model for application title from i18n
2. Create i18n_th and use some Thai text for the application title
3. On file ui5.yaml,  add the following code after line of metadata-name
_resources:
    configuration:
        propertiesFileSourceEncoding: "UTF-8"_
4. Build the application and deploy to system.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.68.1`
- Node.js Version: `{...}`
- npm Version: `{...}`
- OS/Platform: `{...}`
- Browser *(if relevant)*: `Chrome`
- Other information: `{...}`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```

**Comment by RandomByte** [comment] 2019-08-19 10:03
Could you please attach the mentioned `i18n_th` file so that we can reproduce the issue? Thanks!

**Comment by SupayaT** [comment] 2019-08-19 10:20
> Could you please attach the mentioned `i18n_th` file so that we can reproduce the issue? Thanks!

Thanks for your reply. The following url is i18n_th file.
https://drive.google.com/file/d/18zDH-nujEYqdAdFRgnIKoMfKsiL-2dcz/view?usp=sharing

**Comment by RandomByte** [comment] 2019-08-19 11:02
I created this test project: [utf8-test.zip](https://github.com/SAP/ui5-cli/files/3515481/utf8-test.zip)

Execute `npm install` followed by `npm run build` to build the project.

The resulting `dist/i18n_th.properties` file contains the following texts:
- `title=\u0e44\u0e15\u0e40\u0e15\u0e34\u0e49\u0e25` (equals `ไตเติ้ล`)
- `appTitle=\u0e40\u0e17\u0e2a` (equals `เทส`)

Can you confirm that these are the ASCII strings you are seeing in your setup as well?

**Comment by MopJang** [comment] 2019-08-20 02:32
I have the same problem and i tested your test project "utf8-test" in file `dist/i18n_th.properties` is contains texts like ` title=\u0e44\u0e15\u0e40\u0e15\u0e34\u0e49\u0e25` and it works in application area but still display ������ in launchpad shell header following this image below
![image](https://user-images.githubusercontent.com/28567366/63312720-8b074e80-c32c-11e9-8413-aa3430144af0.png)

**Comment by SupayaT** [comment] 2019-08-20 03:04
> I created this test project: [utf8-test.zip](https://github.com/SAP/ui5-cli/files/3515481/utf8-test.zip)
> 
> Execute `npm install` followed by `npm run build` to build the project.
> 
> The resulting `dist/i18n_th.properties` file contains the following texts:
> 
> * `title=\u0e44\u0e15\u0e40\u0e15\u0e34\u0e49\u0e25` (equals `ไตเติ้ล`)
> * `appTitle=\u0e40\u0e17\u0e2a` (equals `เทส`)
> 
> Can you confirm that these are the ASCII strings you are seeing in your setup as well?

As your ASCII strings on i18n is correct with my file Thai text and my project also seem like your result, but it's still not working for the system deployment. 
So, I find my previously build project which works with the deployment, the component-preload has not converted the utf-8 text in file i18n_th to ASCII string. I'm not sure that it may be the cause of this issue.

**Comment by RandomByte** [comment] 2019-08-20 14:19
@MopJang thank you for reporting your findings!

@MopJang @SupayaT, if the unicode escape sequences in the resulting .properties files are correct I suspect this to be an issue with the UI5 runtime or the Fiori Launchpad Shell rather than the UI5 Tooling. In both cases, please raise SAP support incidents so that my colleagues can analyze this in more detail.  
Please refer to this issue.

I'll close this issue for the time being as it seems to be unrelated to the UI5 Tooling.

**Closed by RandomByte** 2019-08-20 14:19 UTC
Labels: information required

**Comment by MopJang** [comment] 2019-08-21 02:49
@RandomByte Can i build the project without convert to ascii?

**Comment by SupayaT** [comment] 2019-08-21 03:22
> @MopJang thank you for reporting your findings!
> 
> @MopJang @SupayaT, if the unicode escape sequences in the resulting .properties files are correct I suspect this to be an issue with the UI5 runtime or the Fiori Launchpad Shell rather than the UI5 Tooling. In both cases, please raise SAP support incidents so that my colleagues can analyze this in more detail.
> Please refer to this issue.
> 
> I'll close this issue for the time being as it seems to be unrelated to the UI5 Tooling.

From your reply, it's true that may be an issue with the UI5 runtime or the Fiori Launchpad Shell, 
but I suspect how the previous version of your tool was work? I think it not the correct solution to raise the issue to SAP to solve and then if SAP gives me a note,  I have to implement it to every destination system right? 

So, I would like to put some code or setting property into ui5.yaml to ignore the encoding of .properties file into ASCII that the reason for this issue. 
Thanks!

**Comment by codeworrior** [comment] 2019-08-21 04:27
The `ui5-cli` allows to exclude tasks during the build. The conversion of properties files is a separate task so you can skip it with

```js
ui5 build --exclude-task=escapeNonAsciiCharacters
```

Nevertheless, I think we should understand why the conversion approach is failing in your scenario but working in all our tests. We decided for that option as it - from our perspective - is the most robust and most consistent one. It does not require special server capabilities (Content header, way how file is read by the server etc.), nor is a special setting in the HTML page needed. And the decision about the format can be taken per app (component) which is helpful in highly modularized scenarios with many apps like SAP's Fiori.

Can you provide us either with a URL of a running app or snippet where we can see the issue or tell us more about the build and server environment that you're using?

**Comment by codeworrior** [comment] 2019-08-21 04:38
One more question: are these texts used for i18n texts in a manifest.json? Because the shell header text to my understanding is taken from the manifest.json.

And if so, are you testing against an ABAP Launchpad?

**Comment by SupayaT** [comment] 2019-08-21 04:59
> The `ui5-cli` allows to exclude tasks during the build. The conversion of properties files is a separate task so you can skip it with
> 
> ```js
> ui5 build --exclude-task=escapeNonAsciiCharacters
> ```
> 
> Nevertheless, I think we should understand why the conversion approach is failing in your scenario but working in all our tests. We decided for that option as it - from our perspective - is the most robust and most consistent one. It does not require special server capabilities (Content header, way how file is read by the server etc.), nor is a special setting in the HTML page needed. And the decision about the format can be taken per app (component) which is helpful in highly modularized scenarios with many apps like SAP's Fiori.
> 
> Can you provide us either with a URL of a running app or snippet where we can see the issue or tell us more about the build and server environment that you're using?

Thanks a lot for your reply, I try and it's work!
For your many questions, I would tell you that maybe my test deployment server environment is Thai language. So, I'm not sure would you like to access my server to solve the runtime environment right? Cause I think your solution so work, compatible with the system environment and completely for me.

**Comment by codeworrior** [comment] 2019-08-21 05:02
Okay, understood. 

Could you then please at least attach the manifest.json that you get from the runtime server to this issue? I suspect the backend replacement of i18n texts in the manifest.json to be the root cause for this issue.

**Comment by SupayaT** [comment] 2019-08-21 05:11
> Okay, understood.
> 
> Could you then please at least attach the manifest.json that you get from the runtime server to this issue? I suspect the backend replacement of i18n texts in the manifest.json to be the root cause for this issue.

{
    "_version": "1.12.0",
    "sap.app": {
        "id": "test.ztest1",
        "type": "application",
        "i18n": "i18n/i18n.properties",
        "applicationVersion": {
            "version": "1.0.0"
        },
        "title": "{{appTitle}}",
        "description": "{{appDescription}}",
        "sourceTemplate": {
            "id": "servicecatalog.connectivityComponentForManifest",
            "version": "0.0.0"
        },
        "dataSources": {
            "C_WORKCENTERPRODCOSTQUERY_CDS": {
                "uri": "/sap/opu/odata/sap/C_WORKCENTERPRODCOSTQUERY_CDS/",
                "type": "OData",
                "settings": {
                    "localUri": ""
                }
            }
        }
    },
    "sap.ui": {
        "technology": "UI5",
        "icons": {
            "icon": "",
            "favIcon": "",
            "phone": "",
            "phone@2": "",
            "tablet": "",
            "tablet@2": ""
        },
        "deviceTypes": {
            "desktop": true,
            "tablet": true,
            "phone": true
        }
    },
    "sap.ui5": {
        "services": {
            "ShellUIService": {
                "factoryName": "sap.ushell.ui5service.ShellUIService"
            }
        },
        "flexEnabled": false,
        "rootView": {
            "viewName": "test.ztest1.view.View1",
            "type": "XML",
            "async": true,
            "id": "View1"
        },
        "dependencies": {
            "minUI5Version": "1.60.1",
            "libs": {
                "sap.ui.layout": {},
                "sap.ui.core": {},
                "sap.m": {}
            }
        },
        "contentDensities": {
            "compact": true,
            "cozy": true
        },
        "models": {
            "i18n": {
                "type": "sap.ui.model.resource.ResourceModel",
                "settings": {
                    "bundleName": "test.ztest1.i18n.i18n"
                }
            },
            "test1": {
                "type": "sap.ui.model.odata.v2.ODataModel",
                "settings": {
                    "defaultOperationMode": "Server",
                    "defaultBindingMode": "OneWay",
                    "defaultCountMode": "Request"
                },
                "dataSource": "C_WORKCENTERPRODCOSTQUERY_CDS",
                "preload": true
            }
        },
        "resources": {
            "css": [
                {
                    "uri": "css/style.css"
                }
            ]
        },
        "routing": {
            "config": {
                "routerClass": "sap.m.routing.Router",
                "viewType": "XML",
                "async": true,
                "viewPath": "test.ztest1.view",
                "controlAggregation": "pages",
                "controlId": "app",
                "clearControlAggregation": false
            },
            "routes": [
                {
                    "name": "RouteView1",
                    "pattern": "RouteView1",
                    "target": [
                        "TargetView1"
                    ]
                }
            ],
            "targets": {
                "TargetView1": {
                    "viewType": "XML",
                    "transition": "slide",
                    "clearControlAggregation": false,
                    "viewId": "View1",
                    "viewName": "View1"
                }
            }
        }
    },
    "sap.platform.abap": {
        "uri": "/sap/bc/ui5_ui5/sap/ztest1/webapp",
        "_version": "1.1.0"
    }
}

**Comment by RandomByte** [comment] 2020-01-22 18:43
We were finally able to reproduce and analyze this issue in a live NetWeaver system 🎉

For anyone facing this issue in an FLP on ABAP environment, please implement **SAP Note [2884219](https://launchpad.support.sap.com/#/notes/2884219)**

If you continue to experience this issue, please let us know here or by raising an OSS ticket.
