### ISSUE TITLE
XML-Namespace is removed in component-preload.js

### ISSUE THREAD

**Issue by hauntedhill** [SAP/ui5-cli#385] opened 2020-11-04 13:00 UTC
## Expected Behavior
The XML files in the component-preload.js should include all needed XML namespaces (as in the original file).

## Current Behavior
If the namespace is only used inside an XML tag then the namespace is removed in the component-preload.js

## Steps to reproduce the issue
1. use the namespace: xmlns:customData="http://schemas.sap.com/sapui5/extension/sap.ui.core.CustomData/1"
2. set attribute in a smarttable: <smartTable:SmartTable id="employee_table" customData:p13nDialogSettings='{filter:{visible:false}}' />
3. run ui5 build
4. In the component-preload.js is the namespace (see 1) removed

## Context
- UI5 Module Version 2.6.1

## Affected components *(if known)*

- [X ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment] 2020-11-04 13:13
Are you sure you tested with UI5 CLI `2.6.1`? This sounds a lot like https://github.com/SAP/ui5-builder/issues/538 which should be resolved in that version. But I'll test it again with your description.

What's the output of `ui5 --version`?

**Comment by codeworrior** [comment] 2020-11-04 13:22
@RandomByte please note that this time the usage of namespaces in _attributes_ is missed. https://github.com/SAP/ui5-builder/issues/538 was about namespaces for _tags_. minify-xml has a separate RegExp for attributes and I guess there's another issue in it.

**Comment by RandomByte** [comment] 2020-11-04 13:32
I was able to reproduce this issue with UI5 CLI `v2.6.1` based on this example: https://github.com/RandomByte/openui5-sample-app/pull/2

Indeed, the namespace is removed in the Component-preload.js, which is not the case with UI5 CLI `v2.5.0`

**Comment by bfmeb** [comment] 2020-11-04 13:53
Facing same issue with namespace xmlns:customData.
Additionally the XML closing tags are corrupted:
- closing xml element with //> instead of />
- closing element is missing at all
In general the XML in Component-preload.js file seems to be corrupted.

**Comment by codeworrior** [comment] 2020-11-04 13:57
As a quick workaround, you can downgrade to UI5 CLI `v2.5.0` until the problem is fixed.

**Comment by RandomByte** [comment] 2020-11-04 13:59
I filed https://github.com/kristian/minify-xml/issues/5 for the root issue in minify-xml.

Re @bfmeb:
> - closing xml element with //> instead of />

This sounds expected. Note that the preload bundle stores the XML in a string. This requires escaping of quotes and slashes.

> - closing element is missing at all

Do you have an example of a source and result XML where this can be observed?

**Comment by kristian** [comment] 2020-11-04 14:19
Taking a look now! Sorry for the delay. 😊

**Comment by kristian** [comment] 2020-11-04 14:27
Fixed with 2.1.4, sorry for any inconvenience caused!

**Comment by RandomByte** [comment] 2020-11-04 14:29
Thanks. I'll verify and create a new UI5 CLI release. Affected projects need to wait for the CLI release.

**Comment by kristian** [comment] 2020-11-04 14:34
> Thanks. I'll verify and create a new UI5 CLI release. Affected projects need to wait for the CLI release.

Found another edge case, if multiple namespaces are used in attributes. Give me 10 more minutes please. I'll also start writing some tests now. Regexes are getting complicated! ;)

**Comment by kristian** [comment] 2020-11-04 17:02
> Thanks. I'll verify and create a new UI5 CLI release. Affected projects need to wait for the CLI release.

Also namespaces in multiple attributes are now detected. Fixed in 2.1.5. Tests have been added to `minify-xml`. Sorry for the inconvenience again!

**Closed** 2020-11-04 17:59 UTC
Labels: bug

**Comment by RandomByte** [comment] 2020-11-04 18:22
This issue is resolved with @ui5/cli [v2.6.2](https://github.com/SAP/ui5-cli/releases/tag/v2.6.2). Thanks for reporting!

**Comment by bfmeb** [comment] 2020-11-05 08:42
Thanks! @ui5/cli v2.6.2 fixes also my issues.

**Comment by hauntedhill** [comment] 2020-11-05 10:40
Thanks 👍
