### ISSUE TITLE
Incorrect update hint for global installs

### ISSUE THREAD

**Issue by piejanssens** [SAP/ui5-cli#374] opened 2020-09-15 09:23 UTC
```
➜  ~ ui5 --version
1.13.1 (from /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli/bin/ui5.js)


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 1.13.1 → 2.4.4    │
   │     Run npm i @ui5/cli to update     │
   │                                      │
   ╰──────────────────────────────────────╯
```

1. installed globally (missing -g)
2. major version update requires explicit major version to be specified. see https://docs.npmjs.com/cli-commands/update.html#updating-globally-installed-packages

FYI `npm i -g @ui5/cli@latest` doesn't upgrade a major version either. `npm i -g @ui5/cli 2` will update to latest (2.4.4).

**Comment by RandomByte** [comment] 2020-09-15 09:53
Hey, could you please share your Node.js and npm versions?

We use [update-notifier](https://github.com/yeoman/update-notifier) for this, which I think should handle this correctly already. @ui5/cli v1.13.1 used [v4.0.0](https://github.com/SAP/ui5-cli/blob/v1.13.1/npm-shrinkwrap.json#L7440-L7441) of that module.

**Comment by piejanssens** [comment] 2020-09-15 10:29
```
➜  ~ npm --version
6.13.4
➜  ~ node --version
v12.15.0
```

**Comment by matz3** [comment] 2020-09-15 11:56
Could you please try to run this and post the printed result?

```shell
cd /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli
node -p "require(\"global-dirs\")"
```

It should log the paths which are used to detect whether the package is installed globally.
Maybe this differs within your setup. I wasn't able to reproduce this with the same CLI version.

**Comment by piejanssens** [comment] 2020-09-16 06:31
```
➜  ~ cd /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli
➜  cli node -p "require(\"global-dirs\")"
{
  npm: {
    prefix: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0',
    packages: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0/lib/node_modules',
    binaries: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0/bin'
  },
  yarn: {
    prefix: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0',
    packages: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0/global/node_modules',
    binaries: '/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0/global/node_modules/.bin'
  }
}
```

**Comment by matz3** [comment] 2020-09-16 07:32
That looks find and the check should detect that the module is installed globally.

Could you please give some more details to allow us reproducing this on our side?
Which linux distribution do you use and how (native / Docker / WSL / ...)?
I was unable to reproduce this with the docker image `node:12.15.0`.

Regarding your second point about major updates:
I could not completely verify that.
When doing `npm i -g @ui5/cli@1.13.1` and then `npm i -g @ui5/cli` (as suggested by the hint if it works correctly) I will get version 2.4.4, as expected.

**Comment by piejanssens** [comment] 2020-09-16 21:07
WSL with Ubuntu 18.04

**Comment by matz3** [comment] 2020-09-17 08:09
Thanks, I'll try to reproduce the issue there.

**Comment by piejanssens** [comment] 2020-09-17 10:17
I went back to 1.13.1 by doing `npm -g uninstall @ui5/cli` then `npm i -g @ui5/cli@1.13.1` and it's no longer showing the update hint:

```
➜  ~ npm i -g @ui5/cli@1.13.1                                                                                                                                           
/home/linuxbrew/.linuxbrew/bin/ui5 -> /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli/bin/ui5.js                                                                   
                                                                                                                                                                        
> core-js@2.6.11 postinstall /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli/node_modules/core-js                                                                  
> node -e "try{require('./postinstall')}catch(e){}"                                                                                                                     
                                                                                                                                                                        
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!                                                        
                                                                                                                                                                        
The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:                                                                       
> https://opencollective.com/core-js                                                                                                                                    
> https://www.patreon.com/zloirock                                                                                                                                      
                                                                                                                                                                        
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)                                                                                
                                                                                                                                                                        
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/@ui5/cli/node_modules/fsevents):                                                           
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})       
                                                                                                                                                                        
+ @ui5/cli@1.13.1                                                                                                                                                       
added 960 packages from 867 contributors in 51.93s                                                                                                                      
➜  ~ ui5 --version                                                                                                                                                      
1.13.1 (from /home/linuxbrew/.linuxbrew/lib/node_modules/@ui5/cli/bin/ui5.js)                                                                                           
➜  ~                                                                                                                                                                    
```

In addition, this time when I follow this with `npm i -g @ui5/cli` as you did it also installs 2.4.4... 😕

**Comment by RandomByte** [comment] 2020-09-21 10:33
> it's no longer showing the update hint

There's a delay of 24 hours from detection until the update hint is displayed: https://github.com/yeoman/update-notifier#how

**Comment by matz3** [comment] 2020-09-21 13:49
I could reproduce the issue with Ubuntu 18.04 on WSL.
It seems to be related to the homebrew installation and how the "global-dirs" package resolves the paths.
The result above is in fact not correct as `/home/linuxbrew/.linuxbrew/Cellar/node@12/12.15.0/lib/node_modules` (from global-dirs) and `/home/linuxbrew/.linuxbrew/lib/node_modules` (where the global packages are installed to) are different folders which is the reason why the global check fails.

I'll collect all details to open an issue in global-dirs, as this is a general problem, not related to our CLI.

**Comment by piejanssens** [comment] 2020-09-21 18:38
@matz3 Nice find!

**Comment by matz3** [comment] 2020-09-22 09:04
Closing this issue, please see https://github.com/sindresorhus/global-dirs/issues/17 for further progress

**Closed by matz3** 2020-09-22 09:04 UTC
Labels: bug
